# Configuration file
# key = value

quarkus:
  http:
    root-path: ${QUARKUS_HTTP_ROOT_PATH:/}

app:
  docker-host: ${DOCKER_HOST:tcp://127.0.0.1:2375}
  default-registry: ${APP_DEFAULT_REGISTRY:docker.io}
  registry-prefix: ${APP_REGISTRY_PREFIXES:/}

docker-api/mp-rest/url: ${FETCH_PROTOCOL:http}://${app.default-registry}
